---
author: "Юрій Клебан"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    highlight-style: github
    code-line-numbers: true
language: _language-ua.yml 
---

# Вступ {.unnumbered}

Фахівці спеціальності економічна кібернетика у майбутньому працюватимуть з великими масивами даних, що накопичуються велизними темпами у даний момент і збиралися у попередні дисятиліття. Підготовка, обробка і трансформація даних у зручний формат прийняття рішень забирає все більше часу, а звичні рашіне інструменти аналізу даних, як наприклад, `Microsoft Excel` не мають достатньо вбудованих можливостей для виконнання задач бізнесу.

На даний час існує велика кількість мов програмування, що інтегруються у суспільні сфери діяльності людини та роботи технічних систем: біоінформатика, а також економіка та бізнес.

Однією з мов програмування, що отримали широке поишення серед економістів-науковців, аналітиків та практиків математичного моделювання (`machine learning`) є мова програмування `(R)`[@r-base]. Свою популярність ця мова програмування здобула завдяки простоті у використанні, доступності (безкоштовні як базові компоненти для написання коду, так і середовища розробки), розширюваності (кожен розробник має  можливість створювати власні пакети та публікувати їх у відкритому доступі).

Основними задачами курсу "Вступ до прграмування в R" є ознайомлення студентів з базовми конструкціями мови програмування R, вивчення способів роботи з найпоширенішими типами даних,  

---





