---
author: "Юрій Клебан"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
---

# Про курс {.unnumbered}

```{r}
#| echo: false#| echo: false#| echo: false#| echo: false#| echo: false#| echo: false
doi <- 324234243
```

Матеріали підготовлені для читання курсу **"Вступ до програмування в R"** `[05.250]` для студентів 1-го року навчання, спеціальності економічна кібернетика.

doi badge / made with quarto badge / r-cran badge / visual studio code badge

---

## Опис навчальної дисципліни

Навчальна дисципліна спрямована на вивчення основ практичного застосування популярної мови [R](@r-cran) для проведення статистичних досліджень в економіці.

У процесі вивчення курсу розглядаються теми, що стосуються теоретичних основ та практичної реалізації алгоритмів завантаження, підготовки та обробки економічних даних.

Місце навчальної дисципліни у підготовці здобувачів: програмні результати дисципліни використовуються під час вивчення таких навчальних дисциплін: "Алгоритми та структури даних", "Аналіз даних в R", "Прикладне математичне моделювання в R". Закріплення на практиці здобутих програмних результатів відбувається під час проходження Навчальної практики з курсу «Економіко-математичне моделювання».


## Мета дисципліни

Мета навчальної дисципліни – формування у студентів теоретичних знань та практичних навичок використання мови програмування R для роботи з даними та базовими структурами мови (типи даних, розгалуження, цикли, функції).

## Дотримання принципів доброчесності

Викладач та слухач цього курсу, як очікується, повинні дотримуватися Кодексу академічної доброчесності університету:

-   [x] будь-яка робота, подана здобувачем протягом курсу, має бути його власною роботою здобувача; не вдаватися до кроків, що можуть нечесно покращити Ваші результати чи погіршити/покращити результати інших здобувачів;

-   [x] якщо буде виявлено ознаки плагіату або іншої недобросовісної академічної поведінки, то студент буде позбавлений можливості отримати передбачені бали за завдання;

-   [x] не публікувати у відкритому доступі відповіді на запитання, що використовуються в рамках курсу для оцінювання знань здобувачів;

-   [x] під час фінальних видів контролю необхідно працювати самостійно; не дозволяється говорити або обговорювати, а також не можна копіювати документи, використовувати електронні засоби отримання інформації.

Порушення академічної доброчесності під час виконання контрольних завдань призведе до втрати балів або вживання заходів, які передбачені Кодексу академічної доброчесності НаУОА.

---

## Рецензування

Внутрішній рецензент:
**Іваненко Іван Іванович**, д.т.н, доцент кафедри економіко-математичного моделювання та інформаціних технологій Національного університету "Острозька акакдемія"

Зовнішній рецензент:
**Іваненко Іван Іванович**, д.т.н, проф. кафедри економіко-математичного моделювання та інформаціних технологій Національного університету "Острозька акакдемія"

---

## Підтримка видання

Частина матеріалів посібника створено у межах проекту <strong>"Підготовка, обробка та ефективне використання даних для наукових досліджень (на основі R)"</strong>, що підтримує Європейський союз за програмою [House of Europe](https://houseofeurope.org.ua/).

---

::: {.callout-note appearance="simple"}
Матеріали курсу створені з використанням ряду технологій:

-   [x] `R` Language @r-cra - безкоштована мова програмування для виконання досліджень у сфері статистики, машинного навчання та візуалізацї результатів.

-   [x] [`Quarto` Book](@quarto) - система для публікації наукових та технічних текстів з відкритим кодом (`R`/`Python`/`Julia`/`Observable`).

-   [x] [`JupyterLab`](@jupyter-lab) - середовище розробки на основі [`Jupyter Notebook`](https://jupyter.org/). `JupyterLab` є розширеним веб-інтерфейсом для роботи з ноутбуками.

-   [x] [`Git`](@git)/[`Github`](@github) - система контролю версій та, відповідно, сервіс для організації зберігання коду, а також публікації статичних сторінок.
:::

---

## Цитування

Для цитування матералів посібника ви можете скористатися `bibtex`-описом:

```bibtex
@book {
  title: "Вступ до програмування в R",
  author: "Юрій Клебан",
  year: 2022,
  doi: "<doi_url>"
}
```

---

*Приміка. Усі логотипи, назви продуктів належать їх власникам.*